class QuestionsSeed

  def self.generate_questions
    questions.each do |question|
      seed = Question.create(question:question)
      puts "Created Question #{seed.question}"
    end
  end

  private
    def self.questions
      ["Does the person appear to not have the similar reactions to the same event as others? Or say things like 'I can't help it'?",
        "Has the person gone out of their way to accommodate superstition or bad luck, rather than a more direct approach",
        "Does the person worry unduly about failure or things that cant be controlled?",
        "Is the person socializing with person(s) that are known destructive or criminal such as vandals, or petty thieves and/or gang members?",
        "Is the person argumentative, self destructive, or prone to throw and slam things",
        "Is the person socializing with person(s) that are known drug users? Is the persons moods very different within a day/week?",
        "For example, destroying others property, verbal abuse or displayed signs of bullying?",
        "Has the persons eating habits changed or they no longer appear interested in eating well or proportionally?",
        "Has the person gained or lost weight without really trying?",
        "Has the person been easily distracted or unproductive at work or on projects? Are there unfinished projects?",
        "Has the person begun to take ambien or sleep aids or complained about not sleeping?",
        "Has the person complained about always being tired and limited their activity to work only?",
        "Does the person act as though everything is out of their control and that nothing can be fixed?",
        "Is the person chronically tired, or lacking energy. Do they turn down invitations more than participate?",
        "Has the person used words like 'I dont deserve to be happy or to have things?'",
        "Has the person put themselves down or apologize for their existence?",
        "Does the person leave things unfinished or reneg on their commitments?",
        "Does the person avoid intimacy and events that previously, the seemed happy to do?",
        "Has the person given up on a hobby, craft or being a fan of something recently?",
        "Has the person stopped doing things that had previously gave them pleasure?",
        "Has the person been quick to anger or negative about people and events in their lives?",
        "Does the person often discuss death, their own or others? Do they display morbid curiosity about the dead?",
        "Does the person feel sadness about seemingly all global and personal issues?",
        "Does the person seem erratic in their energy levels, moving sometimes quickly and slowly with high frequency?",
        "Has the person indicated 'I wish I had never been born' or 'everyone would be better off without me'?",
        "Has the person complained about acheness and chronic fatigue?",
        "Has the person begun taking sleeping aids?",
        "Does the person complain of feeling overwhelmed with sadness?",
        "Has the person's moods changed dramatically in the course of a day or days?",
        "Has the person resisted participating in the activities of life?",
        "Has the person stopped eating or getting food, arranging for proper shelter or food?",
        "Does the person as well as experience periods of high grandeur, also experience deep lows in moods",
        "At times, does the person experience difficulty making seemingly easy choices?",
        "Has the person displayed variations in weight or binge and diet behavior?",
        "Does the person experience deep bouts of sadness,loneliness or depression?",
        "Does the person say things like they are not deserving of the people in their lives or that those people would be better off with out them?",
        "Does the person no longer participate in activities and events they had previously enjoyed?",
        "Does the person indicate that they feel unworthy or doubt themselves obsessively?",
        "Has the person turned down invites in order to stay at home and do nothing?",
        "Does the person have a morbid curiosity about death and talk about it a lot?",
        "Is the person taking sleeping aids or sleeping in a lot?",
        "Does the person seem both sad and wildly energetic?",
        "Does the person express fear that is not justified or seems overwhelmed by their emotions?",
        "Has the person expressed the desire to hurt themselves or those around them? Are they apt to say 'I know how I could kill this person?' Do they seem to plan ways to hurt others?",
        "Has the person become increasingly reclusive and more and more refuses invitations outside of the home?",
        "Has the person's moods changed dramatically in the course of a day or days?",
        "Does the person appear at times unfocused or easily distracted from their work or activities?",
        "Does the person appear at times to be doing all kinds of different projects and work; more than anyone would expect?",
        "During periods of high activity, does the person appear to be staying awake all night or performing with little sleep?",
        "Does the person show poor decisions about the people they share time with or the activities they participate in?",
        "Does the person display tantrums or rage or fits that are disproportionate to the triggers?",
        "Does the person appear to have flights of fancy with shopping, purchasing needless gifts, over partying?",
        "Does the person use grand terms in describing themselves, misrepresent their own abilities and expertise? Appear manic and constantly fidgeting?",
        "Does the person talk to imaginary friends or seemingly to themselves?",
        "Are they abusing drugs or alcohol?",
        "Is the person taking sleeping aids or sleeping in a lot?",
        "Is the person known to go on days long drug binges where they are under the influence of some type of drug for more than one day? ",
        "Has the person had periods of great activity and focus followed by periods of resignation from activities altogether?",
        "Has the person's eating habits changed or they no longer appear interested in eating well or proportionally?",
        "Does the person often forget details important to making decisions? Seemed unfocused or confused about simple choices?",
        "Is the person taking sleeping aids or sleeping in a lot?",
        "Has the person complained of feeling tired or turned down activities because they don't have the energy?",
        "Does the person often feel like they are a burden to others, like they can not contribute in a meaningful way?",
        "Does the person constantly put down their surroundings and don't feel like they can change anything",
        "Are they fidgetety or snap at the slightest provocation?",
        "Has the person stopped doing things that had previously gave them pleasure?",
        "Does the person complain of feeling overwhelmed with sadness?",
        "Does the person seem to be more reclusive in the winter months?",
        "Has the person indicated 'I wish I had never been born' or 'everyone would be better off without me'?",
        "Is the person constantly injured due to 'silly accidents'?",
        "Has the person shown signs of self destruction including cutting, severe hair cuts, burning themselves intentionally?",
        "Has the person shown signs of self destruction including cutting, severe hair cuts, burning themselves intentionally?",
        "Has the person acted out with objects that they poke into themselves?",
        "Do they perform extreme haircuts or pull their eyebrows out?",
        "Do they act out by punching things, people or themselves?",
        "Has the person exhibited signs of bullying, mean behavior to those around them?",
        "Does the person have an alcoholic parent?",
        "Does the person often use flattery to and joking to manipulate those around them?",
        "Is the person focused on flattering others?",
        "Is the person falling into a pattern of trouble with the law or have you noticed small violations of the law without getting caught?",
        "Is the person socializing with person(s) that are known destructive or criminal such as vandals, or petty thieves and/or gang members?",
        "Does the person appear reckless and put themselves and others in harms way?",
        "Has the person since a young age taken pleasure at killing bugs and small animals and has that behavior escalated in either its effect of pleasure or on to larger animals?",
        "Does the person seem to be taking drugs or alcohol to excess?",
        "Is their behavior leading to negative changes in their behavior?",
        "Does this person have a 'bad' reputation for lying or being untrustworthy?",
        "Does the person act without regard or care to who he may be hurting?",
        "Does the person act out and feel above it or constantly angry?",
        "Has the person experienced a trauma where they thought they were left behind? Do they talk about that experience a lot?",
        "Seeks out social interaction, even unhealthy ones like going alone to bad places or interacting with bad people",
        "Has the person's behavior been destructive to their family? Has the family begun to accommodate to the irrational needs of the family?",
        "Has the person gone into sudden rages for no good reason?",
        "Does the person often express boredom or that nothing is worth doing or pursuing?",
        "Does the person seem to impulsively and dangerously jump in out of sexual relationships?",
        "Has the person experienced a trauma where they thought they were left behind? Do they talk about that experience a lot?",
        "Has the person begun to pull away from the family and no longer attempt to interact with loved ones?",
        "Do they act out against themselves?",
        "Has the person experienced sexual, physical, or emotional abuse that you know of?",
        "Does the person seem to have trouble maintaining long-term relationships?",
        "Does the person's mood change dramatically from one day to the next?",
        "Does the person quickly lose interest in things that they were once passionate about?",
        "Does the person seem confused about who they are or where they are?",
        "Does the person express seemingly conflicting information about their own regard for people day over day?",
        "Has the person talked of an imaginary friend, voices they alone hear or see things that aren't there?",
        "Does the person intensly believe made up stories that you know to not be true?",
        "Does the person struggle with explaining how they feel?",
        "Does the person seem uncoordinated or not in complete control of their actions?",
        "Has the person talked of an imaginary friend, voices they alone hear or see things that aren't there?",
        "Do they seem confused or forgetful constantly or beyond reason?",
        "Does the person express thoughts that seem 'out of touch with reality?",
        "Has the person been fidgetedy, distracted or appearing to act without thinking?",
        "Has the person talked about getting things that might be dangerous to them or others?",
        "Does the person seem to be keeping different hours or sleeping during the day and staying up all night? Eating outside of regular meal times?",
        "Does the person go quickly from happy to sad or happy to angry?",
        "Do they feel like they are unworthy of being with others? ",
        "Does the person often feel persecuted by others?",
        "Does the person often talk about people they miss or their own feelings of not belonging?",
        "Has the person begun to give away property and valuables thoughtlessly or haphazardly?",
        "Does the person often seem confused or unable to focus?",
        "Does the person have a family member who has commited suicide?",
        "Has the person exhibited self destructive behavior like cutting or burning?",
        "Does the person seem to be taking drugs or alcohol to excess?",
        "Does the person hhave friends or knows of a few or more people in their community who have committed suicide?",
        "Has the person expressed a preference for how they might like to die?",
        "Has the person turned down invites in order to stay at home and do nothing?",
        "Is the person constantly talking about aging, dying or death?",
        "Is the person constantly talking about aging, dying or death?",
        "Has this person been getting into 'scrapes' with the law or received a DUI or DWI in recent past?",
        "Has the person been unable to move forward from a traumatic event?",
        "Has the person been unable to move past their own physical illness, even while recovered?",
        "Is the person experiencing difficulty obtaining or holding down jobs?",
        "Are they avoiding more and more social contact or turning down invitations in favor of saving home?",
        "Have they experienced a romantic break up?",
        "Does the person seem to be taking drugs or alcohol to excess?",
        "Is the person prone to getting into fights or threatening others directly or indirectly?",
        "Is the person taking sleeping aids or sleeping in a lot?",
        "Does the person move from anger to calmness too quickly?",
        "Has the person suddenly been experiencing a change in grades or school/work is deteriorating?",
        "Does the person talk about being unworthy of the company they are with?",
        "Does the person talk about how they migh die or about hurting themselves?",
        "Does the person feel like they can't help themselves and are a burden to others?",
        "Does the person feel like they can't help themselves and are a burden to others?",
        "Does the person talk about pain that is not caused by injury or that they are unable to articulate?",
        "Has the person acted out as though they are going to die? Created a will, begun to give away important items?",
        "Does the person talk about how they migh die or about hurting themselves?",
        "Does the person continuously turn down social engagements?",
        "Has the person who has recently had a baby been fidgetedy, distracted or appearing to act without thinking?",
        "Is the person who has recently had a baby constantly arranging for help with the baby while she is there or leaving more than necessary?",
        "Is the mother slovenly, home is a mess and baby seems to be crying more than usual?",
        "Does the person who has recently had a baby display erratic eating, like binging and purging or over dieting or over eating?",
        "Does the person who has recently had a baby they feel like they are unworthy of being with others? ",
        "Has the person who has recently had a baby put themselves down or apologize for their existence?",
        "Does the person who has recently had a baby have difficulties with intimacy or relating to others who would either wise be close to them?",
        "Does the person who has recently had a baby have difficulties with intimacy or relating to others who would either wise be close to them?",
        "is the person struggling with arranging the necessities of life for the selves: food, shelter?",
        "Does the person avoid intimacy and events that previously, the seemed happy to do?",
        "Does the person seem confused or unfocused?",
        "Has the person complained about always being tired and limited their activity to work only?",
        "Are they unable to complete simple tasks?",
        "Does the person seem constantly worried or excited?",
        "Has the person indicated 'I wish I had never been born' or 'everyone would be better off without me'?",
        "Is the person taking sleeping aids or sleeping in a lot?",
        "Does the mother seem either too passionate or impassionate about the baby?",
        "Is the person hearing voices or talking to imaginary friends?",
        "Does the person sometimes describe situations or people in ways that do not seem true?",
        "Has the person begun to see things that do not exist?",
        "Does the person dilude themselves into believing they have ailments or injuries without being checked out by a medical professional?",
        "Does the person feel persecuted or victimized by voices that don't exist?",
        "Does the person laugh or cry without real reason?",
        "Is the person hearing voices or talking to imaginary friends?",
        "Do they think that their medicine is working against them?",
        "Has the person been experiencing disconnections from work, school or family due their behavior?",
        "Does the person constantly count their actions? Or rely on repeated behavior for comfort?",
        "Has the person complained of panic attacks?",
        "Has the person become increasingly reclusive and more and more refuses invitations outside of the home?",
        "Does the person fear a repeat attack and go out of their way to avoid repeat circumstances of time, place, etc.?",
        "Does the person seemed troubled or anxious suddenly and with out reason?",
        "Do they feel something awful is going to happen to them or that they are in some sort of danger that doesn't exist?",
        "Does the person express panic and fear toward things that are not a real threat?",
        "Has the person exhibited tantrums or fits of rage?",
        "Does the person express that they do not feel like they belong in the company of those who they prior enjoyed?",
        "Does the person often feel responsible and remorseful for things that are not their fault?",
        "Does the person seem confused about what's happening around them or like things have happened before?",
        "Has the person recently lived through or witnessed a traumatic event?",
        "Is the person taking sleeping aids or sleeping in a lot?",
        "Does the person run about or climb things in inappropriate situations",
        "Are the person's grades deteriorating due to lack of focus or avoidance of the work necessary?",
        "Is the person constantly working on multiple projects?",
        "Does the person shout out to be heard?",
        "Has the person  patternistically failed to meet expectations and commitments?",
        "Does the person look away and lack engagement when conversing?",
        "Has the person been called out at school or work for not thoughtfully doing their work?",
        "Does the person act anxious and uncomfortable in their own skin?",
        "Is the person growing increasingly impatient with waiting or sharing?",
        "Does the person seem confused and is increasingly showing difficulty with organizing simple tasks and events?",
        "Does the person distract others during 'quiet time' or individual activities?",
        "Does the person habitually distract others",
        "Are they constantly jumping from one subject to the next in conversations?",
        "Do the exhibit constant movement, though not necessarily focused of a goal or destination?",
        "Do they often seem confused, distracted or forgetful?",
        "Does the person avoid or disregard direct instruction or known social norms?",
        "Does the person act out without thought to consequences?",
        "Does the person often seem confused and disorganized?",
        "Does the person talk non stop without conversational connections",
        "Has the person expressed paranoia toward strangers or people with little or no relationship to them?",
        "Does the person wear sunglasses to hide glassy or blood shot eyes; do they carry vials of visine?",
        "Does the person seem to be keeping different hours or sleeping during the day and staying up all night? Eating outside of regular meal times?",
        "Has the person stopped taking care of themselves in terms of hygiene, dress? Are they unkempt?",
        "Has the person been missing classes without excuse?",
        "Has the person stopped sharing plans and ideas with you and instead works hard to not disclose what he thinks or does?",
        "Does the person seem to provoke fights or always seem to be getting into them either verbal or physical?",
        "Does the person avoid intimacy and events that previously, the seemed happy to do?",
        "Has this person been getting into 'scrapes' with the law or received a DUI or DWI in recent past?",
        "Is the person constantly agitated and moving or engaging with others?",
        "Has the person switched friends or groups of friends and abandoned interests they once found pleasurable?",
        "Does the person seem angry, negative and lashes out?",
        "Does the person display erratic eating, like binging and purging or over dieting or over eating?",
        "Does the person seem to be drunk, slurring or unable to quite speak?",
        "Does the person seem different or 'not themselves'?",
        "Is the person constantly looking to borrow money froam friends or family?",
        "Has the person's alcohol or substance abuse interrupted his family life or those relationships?",
        "Has the person's drinking or substance abuse resulted in reckless behavior?"

      ]
    end

end

QuestionsSeed.generate_questions
